language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - make generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  local_dir: ./build/html
  on:
    branch: master
