from .page import Page
from .title_page import TitlePage
from .age_distribution_page import AgeDistributionPage
from .categories_distribution_page import CategoriesDistributionPage
from .changes_distribution_page import ChangesDistributionPage
from .problematic_pull_requests_page import ProblematicPullRequestsPage